# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, verbose_name='日期')),
                ('weather', models.CharField(max_length=20, verbose_name='天气')),
                ('temperature_h', models.CharField(max_length=10, verbose_name='最高气温')),
                ('temperature_l', models.CharField(max_length=10, verbose_name='最低气温')),
            ],
            options={
                'verbose_name': '天气预报',
                'verbose_name_plural': '天气预报',
            },
        ),
    ]
