# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.CharField(max_length=20, verbose_name='日期'),
        ),
    ]
