# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20171112_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='temperature_h',
            field=models.CharField(max_length=10, null=True, verbose_name='最高气温'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature_l',
            field=models.CharField(max_length=10, null=True, verbose_name='最低气温'),
        ),
    ]
